trigger:
- none

pool:
  vmImage: ubuntu-latest


stages:
- stage: loadtest
  displayName: azure load testing stage
  jobs:
  - job: loadtest
    displayName: azure load testing job
    steps:
      
    - task: AzureLoadTest@1
      displayName: running load test on geralexgr.com
      inputs:
        azureSubscription: 'geralexgr-azure'
        loadTestConfigFile: 'config/azure-load-testing.yml'
        resourceGroup: 'devops-infra'
        loadTestResource: 'geralexgr-loadtest'