trigger:
- none

pr: none 

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: repo1
      type: git
      name: "projects"
      ref: main

stages:
- stage: devsecops
  displayName: Run DevSecOps checks
  jobs:
  - job: trivy
    displayName: scan container using snyk
    steps:
    - checkout: self
      displayName: Download self repo
      path: "s/Source"

    - checkout: repo1
      displayName: Download projects repo
      path: "s/projects"

    - task: Docker@2
      displayName: build dotnet container application
      inputs:
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/projects/**/Dockerfile'
        arguments: '-t mycustomimage:$(Build.BuildNumber)'

    - task: PowerShell@2
      displayName: print docker images
      inputs:
        targetType: 'inline'
        script: |
          docker image ls

    - task: SnykSecurityScan@1
      displayName: scan container using snyk tool
      inputs:
        serviceConnectionEndpoint: 'snyk-cloud'
        testType: 'container'
        dockerImageName: 'mycustomimage:$(Build.BuildNumber)'
        severityThreshold: 'medium'
        monitorWhen: 'always'
        failOnIssues: true
        organization: 'geralexgr'